name: CustomItemLoader
author: alvin0319
main: alvin0319\CustomItemLoader\CustomItemLoader
version: 3.1.0
api: 3.0.0 # TODO

extensions:
  Core: ">=8.0"

permissions:
  customitemloader.command.rsc:
    default: op
  customitemloader.command:
    default: op
